# Generated by Django 3.1.2 on 2020-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uword', models.CharField(max_length=500)),
                ('utime', models.CharField(max_length=100)),
            ],
        ),
    ]
