# Generated by Django 3.1.2 on 2020-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('uaddress', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('uflag', models.BooleanField(default=False)),
            ],
        ),
    ]
