# Generated by Django 3.1.2 on 2020-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('Now_time', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ask', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uflag',
            field=models.CharField(max_length=20),
        ),
    ]
