# Generated by Django 3.1.2 on 2020-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201116_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisper',
            name='Num_plate',
            field=models.CharField(default=446146024, max_length=30),
        ),
    ]
